specify numpy 1.23.4
Avoid AttributeError: module 'numpy' has no attribute 'object'

From "https://stackoverflow.com/questions/75069062/module-numpy-has-no-attribute-object":

Since version 1.24 of numpy, np.object is deprecated, and needs to be replaced with object (cf. https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations).